### ISSUE TITLE
New Version unity debugger

### ISSUE THREAD

**Issue by nagaohiroki** [nagaohiroki/dotfiles#3]
[815#discussioncomment-8033991](https://github.com/mfussenegger/nvim-dap/discussions/815#discussioncomment-8033991)

https://marketplace.visualstudio.com/items?itemName=visualstudiotoolsforunity.vstuc
Add a breakpoint in vscode and press F5.
After that, when I played Unity I was able to stop at the breakpoint.

checked version:
vscode v1.85.1
Unity v2022.36f1

**Comment by nagaohiroki** [comment]
I tried the new Unity Debugger.
Error occurs while connecting to Unity
[vstuc.log](https://github.com/nagaohiroki/dotfiles/files/13882950/vstuc.log)
(my settings may be wrong)

``` lua
dap.adapters.vstuc= {
	type = 'executable',
	command = vim.env.HOME .. '/AppData/Roaming/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.14~x64/dotnet.exe',
	args = {vim.env.HOME .. '/.vscode/extensions/visualstudiotoolsforunity.vstuc-0.9.3/bin/UnityDebugAdapter.dll'},
	name = 'Attach to Unity',
}
dap.configurations.cs = {
	{
		type = 'vstuc',
		request = 'attach',
		name = 'Attach to Unity',
		-- path = 'UnityProject/Library/EditorInstance.json -- not working?
		logFile = vim.env.HOME .. "/Desktop/vstuc.log",
		endPoint = "127.0.0.1:56912" -- from Unity Editor.log 

	},
}
```

**Comment by nagaohiroki** [comment]
030d510576543e047f5ecd6bedb07430067eaf89

**Comment by nagaohiroki** [comment]
この変更で動くのを確認
https://github.com/mfussenegger/nvim-dap/blob/90616ae6ae40053103dc66872886fc26b94c70c8/lua/dap/session.lua#L995
 { filters = filters, exceptionOptions = exceptionOptions },
to
 { filters = filters, exceptionOptions = exceptionOptions, filterOptions = {} },

**Comment by nagaohiroki** [comment]
filterOptionsについてvstuc側に必須パラメータにしないように問い合わせるのが良さそう。
https://github.com/microsoft/vscode-dotnettools/issues

dap側でsupportsExceptionFilterOptionsをfalseにできる?

**Comment by nagaohiroki** [comment]
デバッグ開始→Unity再生→Unity再生停止をするとデタッチされる以下のエラー確認

```
--> R (stackTrace-24): {"type":"response","request_seq":24,"success":true,"command":"stackTrace","body":{"stackFrames":[{"id":51,"name":"Int32 System.Threading.WaitHandle:WaitOneNative (SafeHandle, UInt32, Boolean, Boolean)","line":0,"column":0},{"id":52,"name":"Boolean System.Threading.WaitHandle:InternalWaitOne (SafeHandle, Int64, Boolean, Boolean)","line":0,"column":0},{"id":53,"name":"Boolean System.Threading.WaitHandle:WaitOne (Int64, Boolean)","line":0,"column":0},{"id":54,"name":"Boolean System.Threading.WaitHandle:WaitOne (Int32, Boolean)","line":0,"column":0},{"id":55,"name":"Boolean System.Threading.WaitHandle:WaitOne ()","line":0,"column":0},{"id":56,"name":"HttpListenerContext System.Net.HttpListener:EndGetContext (IAsyncResult)","line":0,"column":0},{"id":57,"name":"HttpListenerContext System.Net.HttpListener:GetContext ()","line":0,"column":0},{"id":58,"name":"Void UnityEditor.BuildReportRestService:RunServer ()","line":0,"column":0},{"id":59,"name":"Void UnityEditor.BuildReportRestService:RunServerWithRetries (Int32)","line":0,"column":0},{"id":60,"name":"Void UnityEditor.BuildReportRestService:<OnEnable>b__13_0 ()","line":0,"column":0},{"id":61,"name":"Void System.Threading.ThreadHelper:ThreadStart_Context (Object)","line":0,"column":0},{"id":62,"name":"Void System.Threading.ExecutionContext:RunInternal (ExecutionContext, ContextCallback, Object, Boolean)","line":0,"column":0},{"id":63,"name":"Void System.Threading.ExecutionContext:Run (ExecutionContext, ContextCallback, Object, Boolean)","line":0,"column":0},{"id":64,"name":"Void System.Threading.ExecutionContext:Run (ExecutionContext, ContextCallback, Object)","line":0,"column":0},{"id":65,"name":"Void System.Threading.ThreadHelper:ThreadStart ()","line":0,"column":0}],"totalFrames":15},"seq":805}
<--   C (stackTrace-25): {"arguments":{"threadId":773601056},"seq":25,"command":"stackTrace","type":"request"}
--> R (stackTrace-25): {"type":"response","request_seq":25,"success":true,"command":"stackTrace","body":{"stackFrames":[],"totalFrames":0},"seq":806}
<--   C (stackTrace-26): {"arguments":{"threadId":773599840},"seq":26,"command":"stackTrace","type":"request"}
--> R (stackTrace-26): {"type":"response","request_seq":26,"success":true,"command":"stackTrace","body":{"stackFrames":[],"totalFrames":0},"seq":807}
<--   C (stackTrace-27): {"arguments":{"threadId":773601360},"seq":27,"command":"stackTrace","type":"request"}
--> R (stackTrace-27): {"type":"response","request_seq":27,"success":true,"command":"stackTrace","body":{"stackFrames":[],"totalFrames":0},"seq":808}
--> E (thread): {"type":"event","event":"thread","body":{"reason":"exited","threadId":773599840},"seq":809}
--> E (thread): {"type":"event","event":"thread","body":{"reason":"exited","threadId":773600144},"seq":810}
<--   C (variables-28): {"arguments":{"variablesReference":1},"seq":28,"command":"variables","type":"request"}
--> R (variables-28): {"type":"response","request_seq":28,"success":true,"command":"variables","body":{"variables":[{"name":"Active scene","value":"{UnityEngine.SceneManagement.Scene}","type":"UnityEngine.SceneManagement.Scene","variablesReference":8},{"name":"this","value":"\"App (App)\"","type":"App","variablesReference":9},{"name":"this.gameObject","value":"\"App (UnityEngine.GameObject)\"","type":"UnityEngine.GameObject","variablesReference":10},{"name":"inIsNewGame","value":"true","type":"bool","variablesReference":0}]},"seq":811}
<--   C (continue-29): {"arguments":{"threadId":-1223840192,"granularity":"statement"},"seq":29,"command":"continue","type":"request"}
--> R (continue-29): {"type":"response","request_seq":29,"success":true,"command":"continue","body":{"allThreadsContinued":true},"seq":812}
<--   C (stackTrace-30): {"arguments":{"threadId":773601664},"seq":30,"command":"stackTrace","type":"request"}
Stopping due to fatal error: InvalidOperationException: Operation is not valid due to the current state of the object.
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at SyntaxTree.VisualStudio.Unity.Debugger.UnityThread.FrameContexts()
   at SyntaxTree.VisualStudio.Unity.Debugger.UnityThread.EnumFrameInfo(enum_FRAMEINFO_FLAGS dwFieldSpec, UInt32 nRadix, IEnumDebugFrameInfo2& ppEnum)
   at Microsoft.VisualStudio.Unity.AD7DebugAdapter.HandleStackTraceRequest(StackTraceArguments arguments)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.DebugAdapterBase.HandleProtocolRequest(String requestType, Object requestArgs)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.DebugAdapterBase.OnProtocolRequestReceived(Object sender, RequestReceivedEventArgs e)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.OnRequestReceived(String command, IRequestResponder responder)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.DebugAdapterBase.HandleStackTraceRequestAsync(IRequestResponder`2 responder)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.DebugAdapterBase.<InitializeProtocolClient>b__5_45(IRequestResponder`2 r)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.RequestWithResponseInfo`2.InvokeHandler(DebugProtocol protocol, ProtocolRequest request, Object args)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.HandleIncomingRequest(String msg)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.HandleIncomingMessage(String msg)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.ProcessMessageBody()
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.ReaderThreadProc()
```

**Comment by nagaohiroki** [comment]
https://github.com/nagaohiroki/dotfiles/issues/3#issuecomment-2635628577
dapui無効化にすると解消される。根本的な問題は後々調査
